apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vd7rpdh5o-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vd7rpdh5o-go 
  name: vd7rpdh5o-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vd7rpdh5o-go 
